on:
  push:

    paths:
      - 'k8s/**'

jobs:
  linter:
    name: YAML Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./k8s
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Linter YAML Code
        uses: azure/k8s-lint@v2.0
        with:
          manifests: |
              .